
= Contributing

== Download early access previews

.Install from EAP repository
. Open _Settings (or Preferences)_ then _Plugins | ⚙️_
. Select _Manage Plugin Repositories..._
. Enter `https://plugins.jetbrains.com/plugins/list?channel=eap&pluginId=17096`

.Install EAP from disk
.Download the EAP from the https://github.com/bric3/excalidraw-jetbrains-plugin/releases[plugin release page].
. Open _Settings (or Preferences)_ then _Plugins | ⚙️_
. Select _Install Plugin from Disk..._


== Navigating the code base

This plugin has been bootstrapped from the https://github.com/JetBrains/intellij-platform-plugin-template[IntelliJ Platform Plugin Template].
It might be worth tracking upstream change if they can be applied there too.

[source]
----
.
├── .github
│   └── workflows <6>
├── .run <7>
├── CHANGELOG.md <1>
├── excalidraw-assets <2>
├── plugin <3>
├── project-fixture <4>
└── settings.gradle.kts <5>
----
<1> The changelog to manually edit
<2> This the Excalidraw *React* web-app, this a gradle project
<3> This the actual IntelliJ plugin code base, it's a gradle project
<4> Simple project to open in the sand-boxed IDE.
<5> Usual declaration of the gradle sub-projects (`excalidraw-assets` and `plugin`)
<6> GitHub Action workflows
<7> IntelliJ IDEA's run configurations (_Run Plugin_, etc.)

=== Excalidraw React web-app assets

[source]
----
excalidraw-assets
├── build.gradle.kts <1>
├── config-overrides.js <2>
├── gulpfile.js <3>
├── node_modules <9>
├── package.json <4>
├── public <5>
│   └── index.html
├── src <6>
│   ├── App.tsx
│   ├── index.tsx
│   ├── react-app-env.d.ts
│   └── styles.css
├── tsconfig.json <7>
└── yarn.lock <8>
----
<1> The gradle build configuration, configure `node` and `yarn` tasks,
also defines input/output for better cache-ability.
<2> This is a webpack override configuration, used by `react-app-rewired`, in particular it allows to
inline source maps to allow debugging in a JCEF devtools.
<3> This is a _gulp_ script that performs additional inlining after the react app has been built,
these task cannot be easily merged in the webpack config override if that's even possible.
<4> Usual `package.json` that declares dependencies, with unbounded ranges.
<5> The location of the `index.html`
<6> The location of the React app sources in typescript.
<7> Configuration file necessary for typescript.
<8> A Yarn lock file represents the exact dependencies, it allows reproducible builds.
<9> The `node_modules` folder is where the dependencies are downloaded. Its location is hardcoded in `node` or `npm`.


.A note about the Excalidraw React Web App
JS and React are stranger things to me, their official documentation can be overwhelming at first,
I found this https://medium.com/swlh/react-without-create-react-app-setting-up-a-dev-build-from-scratch-fefd5d9d6baa[blog post]
useful to introduce me to basic concepts.

On the same topic here's a https://www.carlrippon.com/creating-react-app-with-typescript-eslint-with-webpack5/[blog post with the typescript angle].


=== Plugin code base

The `plugin` is a usual Gradle project, most of the sources are written in Kotlin.

TODO : describe `plugin.xml`, and package structure.

== Running the plugin in the sand-boxed environment

Use the predefined task `Run Plugin`, whose configuration is saved in the `.run` folder.

=== Plugin DEBUG logs

This plugin is using the diagnostic logger at DEBUG level, that means the log events
will be appended in the usual `idea.log`.

However, the log category has to be configured at DEBUG level, in order to do so

. Run the plugin configuration
. Once the sand-boxed IDE is ready, open _Help | Diagnostic Tools | Debug Log Settings..._
. Enter `#com.github.bric3.excalidraw`

The sand-boxed IDE's log file is located here : `plugin/build/idea-sandbox/system/log/idea.log`.

Once the sandbox has been run once, this configuration will appear in the following file under the following element:

.plugin/build/idea-sandbox/config/options/other.xml
[source,xpath]
----
/application/component[@name='PropertiesComponent']/property[@name='log.debug.categories']
----


=== Inspect UI

The sand-boxed IDE should be launched with internal mode enabled.

Enable UI Inspector : _Tools > Internal Actions > UI > UI Inspector_




== Dependencies source code

Unfortunately only IntelliJ open API sources are available.

There are two things that was useful to grep JCEF (Java Chrominium Embedded Frame)
and `rd` (aka Jetbrains'own reactive distributed library).

.JCEF
In order to access the sources of JCEF, clone [JetBrains/jcef](https://github.com/JetBrains/jcef) repository:
`git clone git@github.com:JetBrains/jcef.git`. Then open a JCEF type
like `org.cef.CefApp`, identify the version of the jar, eg `jcef-81.2.24-gc0b313d-chromium-81.0.4044.113-api-1.1.jar`,
then checkout the matching branch `git checkout cef-81.2.24`. Finally,
point the source location to the `java/` folder at the root of the cloned
repository.

.JetBrains/rd
Part of this code is generated from C/C#, however types that are interacted with
are available in this https://github.com/JetBrains/rd[project]. To get the correct version locate
the actual jar version, eg `rd-core-0.203.181.jar`, checkout branch `203`

- https://github.com/JetBrains/rd/blob/203/rd-kt/rd-core/src/commonMain/kotlin/com/jetbrains/rd/util/reactive/Interfaces.kt[IPropertyView]
- https://github.com/JetBrains/rd/blob/211/rd-kt/rd-core/src/commonMain/kotlin/com/jetbrains/rd/util/reactive/SourceEx.kt[IPropertyView extension methods]
- Lifetime or LifetimeDef types are generated.


== Official documentation

Be sure to check the official documentation

- https://plugins.jetbrains.com/docs/intellij/[IntelliJ Platform SDK]
- https://plugins.jetbrains.com/docs/intellij/internal-ui-inspector.html[UI inspector]
- https://jetbrains.design/intellij/[IntelliJ Platform UI Guidelines]
- https://plugins.jetbrains.com/docs/intellij/api-notable.html[Notable API changes]

- https://github.com/JetBrains/intellij-plugins[IntelliJ plugin]
- https://github.com/JetBrains/intellij-sdk-code-samples[Code samples]
