
= Contributing

== Download early access previews

.Install from EAP repository
. Open _Settings (or Preferences)_ then _Plugins | ⚙️_
. Select _Manage Plugin Repositories..._
. Enter `https://plugins.jetbrains.com/plugins/list?channel=eap&pluginId=17096`

.Install EAP from disk
.Download the EAP from the https://github.com/bric3/excalidraw-jetbrains-plugin/releases[plugin release page].
. Open _Settings (or Preferences)_ then _Plugins | ⚙️_
. Select _Install Plugin from Disk..._


== Navigating the code base

This plugin has been bootstrapped from the https://github.com/JetBrains/intellij-platform-plugin-template[IntelliJ Platform Plugin Template].
It might be worth tracking upstream change if they can be applied there too.


== Plugin DEBUG logs

This plugin is using the diagnostic logger at DEBUG level, that means the log events
will be appended in the usual `idea.log`.

However the log category has to be configured at DEBUG level, in order to do so

. Run the plugin configuration
. Once the sand-boxed IDE is ready, open _Help | Diagnostic Tools | Debug Log Settings..._
. Enter `#com.github.bric3.excalidraw`

The sand-boxed IDE's log file is located here : `plugin/build/idea-sandbox/system/log/idea.log`.

Once the sandbox has been run once, this configuration will appear in the following file under the following element:

.plugin/build/idea-sandbox/config/options/other.xml
[source,xpath]
----
/application/component[@name='PropertiesComponent']/property[@name='log.debug.categories']
----


== Inspect UI

The sand-boxed IDE should be launched with internal mode enabled.

Enable UI Inspector : _Tools > Internal Actions > UI > UI Inspector_




== Dependencies source code

Unfortunately only IntelliJ open API sources are available.

There are two things that was useful to grep JCEF (Java Chrominium Embedded Frame)
and rd (aka Jetbrains'own reactive distributed library).

.JCEF
In order to access the sources of JCEF, clone [JetBrains/jcef](https://github.com/JetBrains/jcef) repository:
`git clone git@github.com:JetBrains/jcef.git`. Then open a JCEF type
like `org.cef.CefApp`, identify the version of the jar, eg `jcef-81.2.24-gc0b313d-chromium-81.0.4044.113-api-1.1.jar`,
then checkout the matching branch `git checkout cef-81.2.24`. Finally,
point the source location to the `java/` folder at the root of the cloned
repository.

.JetBrains/rd
Part of this code is generated from C/C#, however types that are interacted with
are available in this https://github.com/JetBrains/rd[project]. To get the correct version locate
the actual jar version, eg `rd-core-0.203.181.jar`, checkout branch `203`

- https://github.com/JetBrains/rd/blob/203/rd-kt/rd-core/src/commonMain/kotlin/com/jetbrains/rd/util/reactive/Interfaces.kt[IPropertyView]
- https://github.com/JetBrains/rd/blob/211/rd-kt/rd-core/src/commonMain/kotlin/com/jetbrains/rd/util/reactive/SourceEx.kt[IPropertyView extension methods]
- Lifetime or LifetimeDef types are generated.


== Official documentation

Be sure to check the official documentation

- https://plugins.jetbrains.com/docs/intellij/[IntelliJ Platform SDK]
- https://plugins.jetbrains.com/docs/intellij/internal-ui-inspector.html[UI inspector]
- https://jetbrains.design/intellij/[IntelliJ Platform UI Guidelines]
- https://plugins.jetbrains.com/docs/intellij/api-notable.html[Notable API changes]

- https://github.com/JetBrains/intellij-plugins[IntelliJ plugin]
- https://github.com/JetBrains/intellij-sdk-code-samples[Code samples]