compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
